version: '3'

services:
  ogitlab:
    image: gitlab/gitlab-ce:11.8.8-ce.0
    hostname: ogit.kub.xsztn.cn
    #environment:
     # GITLAB_OMNIBUS_CONFIG: |
     #   external_url 'http://git.kub.xsztn.cn'
    volumes:
      - /data0/ogitlab/etc:/etc/gitlab
      - /data0/ogitlab/opt:/var/opt/gitlab
      - /data0/ogitlab/log:/var/log/gitlab
    labels:
      - "traefik.enable=true"
      # GitLab Web 服务
      - "traefik.http.routers.ogitlab.rule=Host(`ogit.kub.xsztn.cn`)"
      - "traefik.http.routers.ogitlab.entrypoints=web"
      - "traefik.http.services.ogitlab.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
    #restart: always
    networks:
      - traefik
networks:
  traefik:
    external: true